story_5/apps/schedule/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'schedule'

urlpatterns = [
    path('', views.index, name="index"),
    path('delete/<int:pk>', views.delete, name="delete"),
    path('detail/<int:pk>', views.detail, name="detail"),
]

story_5/apps/story_1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'story_1'

urlpatterns = [
    path('', views.index, name="index"),
]

story_5/apps/story_4/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.apps import apps

app_name = 'story_4'

urlpatterns = [
    path('', views.index, name="index"),
    path('hobby/', views.hobby, name="hobby"),
]

story_5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_5.apps.story_4.urls')),
    path('story_1/', include('story_5.apps.story_1.urls', namespace='story_1')),
    path('schedule/', include('story_5.apps.schedule.urls', namespace='schedule')),
]

story_5/apps/schedule/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import date

# Create your models here.

TERM = [
    ('Genap', 'Genap'),
    ('Gasal', 'Gasal')
]

class Course(models.Model):
    name = models.CharField(max_length=50)
    lecturer = models.CharField(max_length=50)
    credit = models.IntegerField(
        validators=[
                MinValueValidator(1, message="The minimum credit is 1"), 
                MaxValueValidator(24, message="The maximum credit is 24")
            ]
        )
    description = models.TextField()
    year_parity = models.CharField(max_length=20, choices=TERM)
    start_year = models.IntegerField(
        validators=[
                MinValueValidator(2019, message="The minimum starting year is 2019"), 
                MaxValueValidator(date.today().year, message="The maximum starting year is " + str(date.today().year))
            ]
        )
    room = models.CharField(max_length=50)

    def __str__(self):
        return self.name

story_5/apps/story_1/models.py
from django.db import models

# Create your models here.

story_5/apps/story_4/models.py
from django.db import models

# Create your models here.

story_5/apps/schedule/forms.py
from django import forms
from story_5.apps.schedule.models import Course
from django.forms import TextInput, NumberInput, Textarea, Select

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = "__all__"
        labels = {
            'name': 'Course',
            'year_parity': 'Term',
        }
        widgets = {
            'name': TextInput(attrs={'placeholder': 'Course Name'}),
            'lecturer': TextInput(attrs={'placeholder': 'Lecturer Name'}),
            'credit': NumberInput(attrs={'placeholder': 'How Many Credit'}),
            'description': Textarea(attrs={'placeholder': 'Some Description About The Course'}),
            'year_parity': Select(),
            'start_year': NumberInput(attrs={'placeholder': 'Term Starting Year, E.g 2019'}),
            'room': TextInput(attrs={'placeholder': 'Room Name Or Number'}),
        }

story_5/apps/schedule/views.py
from django.shortcuts import render, get_object_or_404
from .forms import CourseForm
from .models import Course
from django.http import HttpResponseRedirect

# Create your views here.

def index(request):
    courses = Course.objects.all()
    if request.method == "GET":
        form = CourseForm(request.GET or None)
        if (form.is_valid()):
            form.save()
            return HttpResponseRedirect('/schedule')
    else:
        form = CourseForm()
    return render(request, 'schedule/index.html', {'form': form, 'courses': courses})

def delete(request, pk = None):
    course = get_object_or_404(Course, pk=pk)
    if request.method == "GET":
        course.delete()
        return HttpResponseRedirect('/schedule')
    return render(request, 'schedule/index.html')

def detail(request, pk=None):
    course = get_object_or_404(Course, pk=pk)
    if request.method == "GET":
        return render(request, 'schedule/course-detail.html', {'course': course})

story_5/apps/story_1/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'story_1/index.html')

story_5/apps/story_4/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'story_4/index.html')

def hobby(request):
    return render(request, 'story_4/hobby.html')

story_5/apps/schedule/templates/schedule/course-detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Check out my schedule!</title>
{% endblock meta %}

{% block content %}
<section class="p-4 flex flex-col place-items-center">
    <header
		class="font-header text-center text-4xl text-white opacity-50 md:col-span-3 self-center mb-4"
	>
		Details
    </header>
    <div class="w-full max-w-sm text-white font-secondary">
        {% if course %}
        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <div class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                    Course Name:
                </div>
            </div>
            <div class="md:w-2/3">
                {{ course.name }}
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <div class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                    Lecturer: 
                </div>
            </div>
            <div class="md:w-2/3">
                {{ course.lecturer }}
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <div class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                    Credits: 
                </div>
            </div>
            <div class="md:w-2/3">
                {{ course.credit }}
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <div class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                    Description: 
                </div>
            </div>
            <div class="md:w-2/3">
                {{ course.description }}
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <div class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                    Semester: 
                </div>
            </div>
            <div class="md:w-2/3">
                {{ course.year_parity }} - {{ course.start_year }}/{{ course.start_year|add:"1" }}
            </div>
        </div>

        <div class="md:flex md:items-center mb-6">
            <div class="md:w-1/3">
                <div class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                    Room:
                </div>
            </div>
            <div class="md:w-2/3">
                {{ course.room }}
            </div>
        </div>
        
        <div class="md:flex md:items-center">
            <div class="md:w-1/3"></div>
            <div class="md:w-2/3">
                <a href="{% url 'schedule:index' %}" class="btn">Add more courses!</a>
            </div>
        </div>
        {% endif %}
    </div>
</section>

{% endblock content %}

story_5/apps/schedule/templates/schedule/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Check out my schedule!</title>
{% endblock meta %}

{% block content %}	

<section class="p-4">
    <header
		class="font-header text-center text-4xl text-white opacity-50 md:col-span-3 self-center mb-4"
	>
		Course
    </header>
    <div class="grid grid-cols-1 md:grid-cols-2 align-center justify-center">
        <div class="text-white font-secondary m-4 space-y-4 w-full max-w-sm md:max-w-xl place-self-center">
            <div class="text-center text-lg m-4">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="text-white font-secondary border border-white px-4 py-3 rounded relative m-4" style="background-color:#F15025">
                                <span class="block sm:inline">{{ error }}</span>
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
            </div>
            <form action="{% url 'schedule:index' %}" method="GET">
                {% csrf_token %}
                <div class="frm">
                    <div class="md:w-1/3">
                            {{ form.name.label_tag }}
                    </div>
                    <div class="md:w-2/3">
                        {{ form.name }}
                    </div>
                </div>

                <div class="frm">
                    <div class="md:w-1/3">
                            {{ form.lecturer.label_tag }}
                    </div>
                    <div class="md:w-2/3">
                        {{ form.lecturer }}
                    </div>
                </div>

                <div class="frm">
                    <div class="md:w-1/3">
                            {{ form.credit.label_tag }}
                    </div>
                    <div class="md:w-2/3">
                        {{ form.credit }}
                    </div>
                </div>

                <div class="frm">
                    <div class="md:w-1/3">
                            {{ form.description.label_tag }}
                    </div>
                    <div class="md:w-2/3">
                        {{ form.description }}
                    </div>
                </div>

                <div class="frm">
                    <div class="md:w-1/3">
                            {{ form.year_parity.label_tag }}
                    </div>
                    <div class="md:w-2/3 flex space-x-2">
                        <div class="w-1/4">
                            {{ form.year_parity }}
                        </div>
                        <div class="w-3/4">
                            {{ form.start_year }}
                        </div>
                    </div>
                </div>

                <div class="frm">
                    <div class="md:w-1/3">
                            {{ form.room.label_tag }}
                    </div>
                    <div class="md:w-2/3">
                        {{ form.room }}
                    </div>
                </div>

                <div class="md:flex md:items-center">
                    <div class="md:w-1/3"></div>
                    <div class="md:w-2/3">
                        <input type="submit" value="Submit" class="btn">
                    </div>
                </div>
            </form>
        </div>
        <table class="table-auto text-white font-secondary m-4 text-center">
            <thead>
                <tr>
                    <th class="px-4 py-2">Course Name</th>
                    <th class="px-4 py-2">Lecturer</th>
                    <th class="px-4 py-2"></th>
                    <th class="px-4 py-2"></th>
                </tr>
            </thead>
            <tbody>
                {% if courses %}
                    {% for course in courses %}
                        <tr>
                            <td class="border px-4 py-2">{{ course.name }}</td>
                            <td class="border px-4 py-2">{{ course.lecturer }}</td>
                            <td class="px-4 py-2 align-center flex flex-col">
                                <a href="{% url 'schedule:detail' course.id %}" class="btn">Detail</a>
                                <a  href="{% url 'schedule:delete' course.id %}" 
                                    class="btn" 
                                    style="background-color:#F15025">
                                Delete
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>
</section>

{% endblock content %}

story_5/apps/story_1/templates/story_1/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'story_1/css/index.css' %}"
    />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'story_1/images/story1_favicon.png' %}"
    />
    <!--Load fonts-->
    <link
      href="https://fonts.googleapis.com/css2?family=Fira+Sans+Condensed&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Overpass&display=swap"
      rel="stylesheet"
    />
    <title>Story 1 - Portfolio</title>
  </head>

  <body>
    <div class="container">
      <div class="boxes">
        <div class="left-side">
          <div class="box-detail">
            <img
              src="{% static 'story_1/images/profile-picture.jpg' %}"
              alt="Profile picture"
              height="100vh"
              width="100vw"
            />
            <div class="section1">
              <h1><b>Teofanus Gary Setiawan</b></h1>
              <h5>Computer Science - University of Indonesia</h5>
            </div>

            <div class="section2">
              <div class="left">
                <h2>NPM:</h2>
                <h2>Batch:</h2>
                <h2>Hobi:</h2>
              </div>
              <div class="right">
                <h2>1906400160</h2>
                <h2>Maung - 2019</h2>
                <h2>Makan, nonton</h2>
              </div>
            </div>
          </div>
          <div class="box-social-media">
            <a
              class="item"
              href="https://www.instagram.com/garyteofanus/"
              target="_blank"
              ><img src="{% static 'story_1/images/instagram-icon.png' %}"
              alt="Instagram"</a
            >
            <a
              class="item"
              href="https://twitter.com/garyteofanus"
              target="_blank"
              ><img src="{% static 'story_1/images/twitter-icon.png' %}"
              alt="Twitter"</a
            >
            <a
              class="item"
              href="https://github.com/garyteofanus"
              target="_blank"
              ><img src="{% static 'story_1/images/github-icon.svg' %}" alt="GitHub"</a
            >
            <a
              class="item"
              href="https://www.linkedin.com/in/garyteofanus/"
              target="_blank"
              ><img src="{% static 'story_1/images/linkedin-icon.png' %}"
              alt="LinkedIn"</a
            >
            <a class="item" href="mailto: garyteofanus@gmail.com"
              ><img src="{% static 'story_1/images/gmail-icon.png' %}" alt="Email"
            /></a>
          </div>
        </div>

        <div class="right-side">
          <div class="box-about-me">
            <p>
              An aspiring computer scientist. Interested in security and
              programming. Currently on my third semester and having a hard
              time😭
            </p>
          </div>
          <div class="box-education-timeline">
            <div class="education-timeline-container">
              <div class="timeline-item" date-is="2019 - Now">
                <h3>Faculty of Computer Science, University of Indonesia</h3>
              </div>
              <div class="timeline-item" date-is="2016 - 2019">
                <h3>SMAK 1 BPK Penabur Bandung Highschool</h3>
              </div>
              <div class="timeline-item" date-is="2013 - 2016">
                <h3>SMP Talenta Bandung</h3>
              </div>
              <div class="timeline-item" date-is="2007 - 2013">
                <h3>SD Talenta Bandung</h3>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

story_5/apps/story_4/templates/story_4/about.html
{% load static %}
<section
	id="about-me"
	class="flex flex-col md:flex-row bg-green-dark p-4"
>
	<header class="header-right">
		ABOUT ME
	</header>
	<div class="flex justify-center content-center md:w-48 h-48 flex-none m-4">
		<img
			src="{% static 'story_4/images/Profile.png' %}"
			alt="Profile Picture"
			class="rounded-full object-contain"
		/>
	</div>
	<div class="m-4 text-white font-tertiary">
		<p>Hello! 👋</p>
		<br />
		<p>
			My name is Teofanus Gary Setiawan. I’m a sophomore computer
			science student at University of Indonesia. I’m also an avid
			coffe lover to help me in my sleepless nights.
		</p>
		<br />
		<p>
			I have some
			<a
				class="btn"
				href="{% url 'story_4:hobby' %}"
				rel="noopener noreferrer"
				>hobby</a
			>
			that I like to do when I’m not busy programming.
		</p>
		<br />
		<p>My field of interest are programming and math.</p>
		<br />
		<p>If any chance you would like to see what course I took this semester, you can click 
			<a
				class="btn"
				href="{% url 'schedule:index' %}"
				rel="noopener noreferrer"
				>here</a
			>
		</p>
	</div>
</section>

story_5/apps/story_4/templates/story_4/projects.html
{% load static %}
<section
	id="projects"
	class="flex flex-col md:flex-row bg-green-light p-4"
>
	<header class="header-left">
		PROJECTS
	</header>

	<div class="flex flex-col md:flex-row flex-wrap">
		<article class="card p-4 md:w-56">
			<h3 class="col-span-2 text-2xl font-secondary">PokeProject</h3>
			<p class="text-center col-span-2 font-tertiary pt-8 pb-8">
				Simple website of fun quizzes about pokemon and other stuff
			</p>
			<div class="flex flex-row place-content-center space-x-4 pt-4">
				<a
					href="http://poke-project.herokuapp.com/"
					target="_blank"
					class="flex flex-row space-x-2"
					rel="noopener noreferrer"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-globe w-6 h-6 self-center"
						viewBox="0 0 24 24"
					>
						<circle cx="12" cy="12" r="10" />
						<path
							d="M2 12h20M12 2a15 15 0 014 10 15 15 0 01-4 10 15 15 0 01-4-10 15 15 0 014-10z"
						/>
					</svg>
					<h5 class="self-center font-secondary">Live Site</h5>
				</a>
				<a
					href="https://github.com/garyteofanus/pokeproject"
					target="_blank"
					rel="noopener noreferrer"
					class="flex flex-row space-x-2"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-github w-6 h-6 self-center"
						viewBox="0 0 24 24"
					>
						<path
							d="M9 19c-5 2-5-2-7-3m14 6v-4a3 3 0 00-1-2c3-1 7-2 7-7a5 5 0 00-2-4 5 5 0 000-4l-4 1a13 13 0 00-7 0L5 1a5 5 0 000 4 5 5 0 00-1 4c0 5 3 6 6 7a3 3 0 00-1 2v4"
						/>
					</svg>
					<h5 class="self-center font-secondary">Repo</h5>
				</a>
			</div>
		</article>

		<article class="card p-4 md:w-56">
			<h3 class="col-span-2 text-2xl font-secondary">Story 1</h3>
			<p class="text-center col-span-2 font-tertiary pt-8 pb-8">
				First assignment on Web Programming and Design Course
			</p>
			<div class="flex flex-row place-content-center space-x-4 pt-4">
				<a
					href="{% url 'story_1:index' %}"
					target="_blank"
					class="flex flex-row space-x-2"
					rel="noopener noreferrer"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-globe w-6 h-6 self-center"
						viewBox="0 0 24 24"
					>
						<circle cx="12" cy="12" r="10" />
						<path
							d="M2 12h20M12 2a15 15 0 014 10 15 15 0 01-4 10 15 15 0 01-4-10 15 15 0 014-10z"
						/>
					</svg>
					<h5 class="self-center font-secondary">Live Site</h5>
				</a>
				<a
					href="https://gitlab.com/story-ppw/story-1"
					target="_blank"
					rel="noopener noreferrer"
					class="flex flex-row space-x-2"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-github w-6 h-6 self-center"
						viewBox="0 0 24 24"
					>
						<path
							d="M9 19c-5 2-5-2-7-3m14 6v-4a3 3 0 00-1-2c3-1 7-2 7-7a5 5 0 00-2-4 5 5 0 000-4l-4 1a13 13 0 00-7 0L5 1a5 5 0 000 4 5 5 0 00-1 4c0 5 3 6 6 7a3 3 0 00-1 2v4"
						/>
					</svg>
					<h5 class="self-center font-secondary">Repo</h5>
				</a>
			</div>
		</article>

		<article class="card p-4 md:w-56">
			<h3 class="col-span-2 text-2xl font-secondary">TP4 DDP1</h3>
			<p class="text-center col-span-2 font-tertiary pt-8 pb-8">
				Web version of TP3 from Basics of Programming course
			</p>
			<div class="flex flex-row place-content-center space-x-4 pt-4">
				<a
					href="https://tp4-ddp1.herokuapp.com/"
					target="_blank"
					rel="noopener noreferrer"
					class="flex flex-row space-x-2 cursor-not-allowed"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-globe w-6 h-6 self-center"
						viewBox="0 0 24 24"
					>
						<circle cx="12" cy="12" r="10" />
						<path
							d="M2 12h20M12 2a15 15 0 014 10 15 15 0 01-4 10 15 15 0 01-4-10 15 15 0 014-10z"
						/>
					</svg>
					<h5 class="self-center font-secondary">Live Site</h5>
				</a>
				<a
					href="https://github.com/garyteofanus/programming-assignment-4"
					target="_blank"
					rel="noopener noreferrer"
					class="flex flex-row space-x-2"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-github w-6 h-6 self-center"
						viewBox="0 0 24 24"
					>
						<path
							d="M9 19c-5 2-5-2-7-3m14 6v-4a3 3 0 00-1-2c3-1 7-2 7-7a5 5 0 00-2-4 5 5 0 000-4l-4 1a13 13 0 00-7 0L5 1a5 5 0 000 4 5 5 0 00-1 4c0 5 3 6 6 7a3 3 0 00-1 2v4"
						/>
					</svg>
					<h5 class="self-center font-secondary">Repo</h5>
				</a>
			</div>
		</article>

		<article class="card text-2xl p-4 place-items-center md:w-56">
			<h3 class="font-secondary">More Coming Soon ...</h3>
		</article>
	</div>
</section>

story_5/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Basic Page Needs
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
	<meta charset="utf-8" />

	{% block meta %}
	<!-- Title for each page goes here -->
	{% endblock meta %}

	<meta name="Story 3" content="" />
	<meta name="Teofanus Gary Setiawan" content="" />

	<!-- Mobile Specific Metas
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<!-- FONT
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
	<link
		href="//fonts.googleapis.com/css?family=Raleway&display=swap"
		rel="stylesheet"
		type="text/css"
	/>
	<link
		href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@400;800&display=swap"
		rel="stylesheet"
		type="text/css"
	/>
	<link
		href="https://fonts.googleapis.com/css2?family=Signika+Negative&display=swap"
		rel="stylesheet"
		type="text/css"
	/>
	<link
		href="https://fonts.googleapis.com/css2?family=Sarala&display=swap"
		rel="stylesheet"
		type="text/css"
	/>

	<!-- CSS
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
	<link rel="stylesheet" href="{% static 'css/index.css' %}" />

	<!-- Favicon
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
	<link
		rel="icon"
		type="image/png"
		href="{% static 'images/Logo.png' %}"
	/>
</head>

<body class="antialiased bg-green-dark relative min-h-screen">
  	<!-- Navbar goes here -->
	<nav
		class="flex flex-row text-orange-dark font-secondary justify-around p-4 bg-green-darker"
	>
		<a href="{% url 'story_4:index' %}" class="hover:font-bold">Home</a>
		<a href="/#about-me" class="hover:font-bold">About Me</a>
		<a href="/#projects" class="hover:font-bold">Projects</a>
		<a href="/#skills" class="hover:font-bold">Skills</a>
		<a href="/#contacts" class="hover:font-bold">Contact</a>
	</nav>

	<div class="pb-24">
		{% block content %}
		<!-- Content goes here -->
		{% endblock content %}
	</div>

  	<!-- Footer goes here -->
  	<footer
		id="contacts"
		class="grid grid-rows-2 place-items-center space-y-2 p-4 text-white bg-green-darker absolute bottom-0 w-full h-24"
	>
		<ul class="flex flex-row space-x-2">
			<li>
				<a
					href="https://www.linkedin.com/in/garyteofanus/"
					target="_blank"
					rel="noopener noreferer"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-linkedin w-8 h-8"
						viewBox="0 0 24 24"
					>
						<path
							d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"
						/>
						<circle cx="4" cy="4" r="2" />
					</svg>
				</a>
			</li>
			<li>
				<a
					href="https://github.com/garyteofanus"
					target="_blank"
					rel="noopener noreferer"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-github w-8 h-8"
						viewBox="0 0 24 24"
					>
						<path
							d="M9 19c-5 2-5-2-7-3m14 6v-4a3 3 0 00-1-2c3-1 7-2 7-7a5 5 0 00-2-4 5 5 0 000-4l-4 1a13 13 0 00-7 0L5 1a5 5 0 000 4 5 5 0 00-1 4c0 5 3 6 6 7a3 3 0 00-1 2v4"
						/>
					</svg>
				</a>
			</li>
			<li>
				<a
					href="https://www.instagram.com/garyteofanus/"
					target="_blank"
					rel="noopener noreferer"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-instagram w-8 h-8"
						viewBox="0 0 24 24"
					>
						<rect
							x="2"
							y="2"
							width="20"
							height="20"
							rx="5"
							ry="5"
						/>
						<path d="M16 11a4 4 0 11-3-3 4 4 0 013 3zM18 7h0" />
					</svg>
				</a>
			</li>
			<li>
				<a
					href="mailto:garyteofanus@gmail.com"
					target="_blank"
					rel="noopener noreferer"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-mail w-8 h-8"
						viewBox="0 0 24 24"
					>
						<path d="M4 4h16l2 2v12l-2 2H4l-2-2V6l2-2z" />
						<path d="M22 6l-10 7L2 6" />
					</svg>
				</a>
			</li>
		</ul>
		<p class="font-secondary">
			Made with 💖 by Teofanus Gary Setiawan
		</p>
	</footer>
</body>
</html>